Global styles
GDUMA/Wikiuma pull request #80
Opened 2021-05-16 23:22 UTC by rubenjr0

close #77 
Faltaría ir añadiendo más colores y ajustar algunas variables

2021-05-16 23:25 UTC, rubenjr0 commented
Creo que sería buena idea borrar los archivos de bootstrap que no sean relevantes (package.json, etc)

2021-05-17 00:12 UTC, Charly6596 requested changes
@rubenjr0 perfecto, qué currazo! :rocket:

Solo tres cosillas,
- Al poner los archivos scss en la carpeta static, no se estarían añadiendo a la web?
- Yo arreglaría el header en esta PR más que nada porque se ha roto con esto mismo y estaríamos añadiendo algo roto al historial.
- Estaría bien quitar los archivos antes de hacer el merge.

Subo aquí la imagen para que conste:
![image](https://user-images.githubusercontent.com/13708100/118417528-b6ab9a00-b6b4-11eb-8ee7-3c39207e3c64.png)

2021-05-17 00:26 UTC, rubenjr0 commented
Perfecto, en cuanto esté listo subo el commit y aviso.

2021-05-19 18:28 UTC, Charly6596 approved these changes

2021-05-19 18:30 UTC, merged